In [3]:
import pandas as pd
import numpy as np

In [4]:
df_chicago = pd.read_csv("listings_chicago.csv.gz.csv")
df_neworleans = pd.read_csv("listings_neworleans.csv.gz.csv")

In [5]:
df_chicago['city'] = 'Chicago'
df_neworleans['city'] = 'New Orleans'

In [6]:
df= pd.concat([df_chicago , df_neworleans], ignore_index = True)

In [7]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,city
0,19091,https://www.airbnb.com/rooms/19091,20250911031349,2025-09-11,city scrape,Fully Furnished Cozy Apartment,This cozy space is a wonder of post-Katrina re...,"NorthWest Carrollton, where this apartment is ...",https://a0.muscache.com/pictures/a5fdfd3b-5d81...,72880,...,4.68,4.91,"25-NSTR-11772, 25-OSTR-11151",f,1,1,0,0,2.72,Chicago
1,71624,https://www.airbnb.com/rooms/71624,20250911031349,2025-09-11,city scrape,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",https://a0.muscache.com/pictures/37488608/8cc1...,367223,...,4.84,4.89,"21-RSTR-18609, 22-OSTR-20720",f,1,1,0,0,1.78,Chicago
2,74498,https://www.airbnb.com/rooms/74498,20250911031349,2025-09-11,city scrape,Maison Marais 1,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",https://a0.muscache.com/pictures/73591836/a1f5...,391462,...,4.67,4.85,23-XSTR-13082,f,3,3,0,0,3.75,Chicago
3,79536,https://www.airbnb.com/rooms/79536,20250911031349,2025-09-11,previous scrape,FeelAtHomeInNewOrleans-PrivateApt,"Safe, clean & functional!! Front porch and gat...","I love that it's down to earth, welcoming, his...",https://a0.muscache.com/pictures/f1037ebf-1573...,428362,...,4.56,4.87,"23-NSTR-15067, 24-OSTR-20882",t,1,1,0,0,4.57,Chicago
4,79609,https://www.airbnb.com/rooms/79609,20250911031349,2025-09-11,city scrape,Bywater's Original & Finest,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",https://a0.muscache.com/pictures/5c5da2eb-7434...,428909,...,4.84,4.94,"23-ISTR-02823, 23-OSTR-02823",f,1,1,0,0,2.86,Chicago

In [8]:
df.shape

(14888, 80)

In [9]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'city'],
      dtype='object')

In [10]:
df = df[['id','city','neighbourhood','latitude','longitude',
         'property_type','room_type','price',
         'number_of_reviews','reviews_per_month',
         'host_id','host_name','availability_365',
         'calculated_host_listings_count']]

In [11]:
df.shape

(14888, 14)

In [12]:
df.columns

Index(['id', 'city', 'neighbourhood', 'latitude', 'longitude', 'property_type',
       'room_type', 'price', 'number_of_reviews', 'reviews_per_month',
       'host_id', 'host_name', 'availability_365',
       'calculated_host_listings_count'],
      dtype='object')

In [13]:
df.isnull().sum()

id                                   0
city                                 0
neighbourhood                     6030
latitude                             0
longitude                            0
property_type                        0
room_type                            0
price                             2422
number_of_reviews                    0
reviews_per_month                 2580
host_id                              0
host_name                            4
availability_365                     0
calculated_host_listings_count       0
dtype: int64

In [14]:
df['neighbourhood'].fillna('Unknown',inplace = True)

C:\Users\sriva\AppData\Local\Temp\ipykernel_23096\1282792106.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['neighbourhood'].fillna('Unknown',inplace = True)

In [15]:
df.isnull().sum()

id                                   0
city                                 0
neighbourhood                        0
latitude                             0
longitude                            0
property_type                        0
room_type                            0
price                             2422
number_of_reviews                    0
reviews_per_month                 2580
host_id                              0
host_name                            4
availability_365                     0
calculated_host_listings_count       0
dtype: int64

In [16]:
df.dropna(subset=['price'],inplace = True)

In [17]:
df.dropna(subset=['host_id'],inplace = True)
df.dropna(subset=['host_name'], inplace=True)

In [18]:
df['reviews_per_month'].fillna(0, inplace=True)

C:\Users\sriva\AppData\Local\Temp\ipykernel_23096\2638918283.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reviews_per_month'].fillna(0, inplace=True)

In [19]:
df.isnull().sum()
#“I removed irrelevant columns like description and URLs because they were not required for my analysis and would not add value to the dashboard.”

id                                0
city                              0
neighbourhood                     0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
price                             0
number_of_reviews                 0
reviews_per_month                 0
host_id                           0
host_name                         0
availability_365                  0
calculated_host_listings_count    0
dtype: int64

In [20]:
# Reason : “I handled missing values carefully by dropping critical missing values like price, while imputing non-critical ones like neighbourhood to avoid data loss.”

In [21]:
df['price'].head()
df.dtypes

id                                  int64
city                               object
neighbourhood                      object
latitude                          float64
longitude                         float64
property_type                      object
room_type                          object
price                              object
number_of_reviews                   int64
reviews_per_month                 float64
host_id                             int64
host_name                          object
availability_365                    int64
calculated_host_listings_count      int64
dtype: object

In [22]:
df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\sriva\AppData\Local\Temp\ipykernel_23096\2337335738.py:1: SyntaxWarning: invalid escape sequence '\$'
  df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)

In [23]:
df.dtypes

id                                  int64
city                               object
neighbourhood                      object
latitude                          float64
longitude                         float64
property_type                      object
room_type                          object
price                             float64
number_of_reviews                   int64
reviews_per_month                 float64
host_id                             int64
host_name                          object
availability_365                    int64
calculated_host_listings_count      int64
dtype: object

In [63]:
df['price_category'] = pd.cut(
    df['price'],
    bins=[0,100,300,1000,60000],
    labels=['Low','Medium','High','Luxury']
)

In [67]:
df[['price','price_category']].head()

   price price_category
0   61.0            Low
1  150.0         Medium
2   85.0            Low
4   84.0            Low
5   80.0            Low

In [78]:
df['price_category'].value_counts()

price_category
Medium    6356
Low       4210
High      1644
Luxury     254
Name: count, dtype: int64

In [80]:
df.to_csv(r"C:\Users\sriva\Desktop\airbnb_dashboard_ready_v1.csv", index=False)

In [ ]:
#“I created a price_category feature to segment listings into meaningful groups, making analysis and visualization easier.”